name: Build Flet EXE
on:
  push:
    branches: [ main ]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install flet flet-desktop pyinstaller
      - name: Build EXE with PyInstaller
        run: pyinstaller --noconfirm --onefile --noconsole --name "PasswordGenerator" --collect-all flet --collect-all flet_desktop main.py
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: PasswordGenerator-EXE
          path: dist/PasswordGenerator.exe
