name: Build Flet EXE
on:
  push:
    branches: [ main ]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Build EXE with PyInstaller
        run: pyinstaller --noconfirm --onefile --windowed --name "PasswordGenerator" --hidden-import=flet_desktop --collect-all flet main.py
      - name: Zip EXE
        run: Compress-Archive -Path dist/PasswordGenerator.exe -DestinationPath PasswordGenerator-EXE.zip
      - uses: actions/upload-artifact@v4
        with:
          name: PasswordGenerator-EXE
          path: PasswordGenerator-EXE.zip
