name: Build Flet EXE
on:
  push:
    branches: [ main ]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Flet
        run: pip install flet # <-- هاد السطر هو اللي كان ناقص
      - name: Build EXE
        run: flet build windows
      - name: Zip EXE
        run: Compress-Archive -Path build/windows/runner/Release -DestinationPath PasswordGenerator-EXE.zip
      - uses: actions/upload-artifact@v4
        with:
          name: PasswordGenerator-EXE
          path: PasswordGenerator-EXE.zip
